# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from weatherflow_openapi.models.station_item import StationItem  # noqa: E501

class TestStationItem(unittest.TestCase):
    """StationItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StationItem:
        """Test StationItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StationItem`
        """
        model = StationItem()  # noqa: E501
        if include_optional:
            return StationItem(
                location_item_id = 55,
                station_id = 67,
                device_id = 55,
                item = 'air_temperature_humidity'
            )
        else:
            return StationItem(
        )
        """

    def testStationItem(self):
        """Test StationItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
