# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from weatherflow_openapi.models.observation_set import ObservationSet  # noqa: E501

class TestObservationSet(unittest.TestCase):
    """ObservationSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObservationSet:
        """Test ObservationSet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObservationSet`
        """
        model = ObservationSet()  # noqa: E501
        if include_optional:
            return ObservationSet(
                status = weatherflow_openapi.models.status.Status(
                    status_code = 0, 
                    status_message = 'SUCCESS', ),
                device_id = 59.0,
                type = 'obs_air',
                obs = [
                    [
                        1.337
                        ]
                    ]
            )
        else:
            return ObservationSet(
        )
        """

    def testObservationSet(self):
        """Test ObservationSet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
