# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from weatherflow_openapi.models.better_forecast import BetterForecast  # noqa: E501

class TestBetterForecast(unittest.TestCase):
    """BetterForecast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetterForecast:
        """Test BetterForecast
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetterForecast`
        """
        model = BetterForecast()  # noqa: E501
        if include_optional:
            return BetterForecast(
                status = weatherflow_openapi.models.status.Status(
                    status_code = 0, 
                    status_message = 'SUCCESS', ),
                current_conditions = weatherflow_openapi.models.better_forecast_current_conditions.BetterForecastCurrentConditions(
                    time = 1608668142, 
                    conditions = 'Clear', 
                    icon = 'clear-day', 
                    air_temperature = 67.0, 
                    sea_level_pressure = 30.195, 
                    station_pressure = 30.079, 
                    pressure_trend = 'falling', 
                    relative_humidity = 55.0, 
                    wind_avg = 3.2, 
                    wind_direction = 15.0, 
                    wind_direction_cardinal = 'NNE', 
                    wind_direction_icon = 'wind-rose-nne', 
                    wind_gust = 3.4, 
                    solar_radiation = 22.0, 
                    uv = 0.0, 
                    brightness = 2582.0, 
                    feels_like = 68.9, 
                    dew_point = 50.0, 
                    wet_bulb_temperature = 57.0, 
                    delta_t = 10.0, 
                    air_density = 0.08, 
                    lightning_strike_count_last_1hr = 0.0, 
                    lightning_strike_count_last_3hr = 1.0, 
                    lightning_strike_last_distance = 7.0, 
                    lightning_strike_last_distance_msg = '6 - 8 mi', 
                    lightning_strike_last_epoch = 1608150959, 
                    precip_accum_local_day = 0.0, 
                    precip_accum_local_yesterday = 0.0, 
                    precip_minutes_local_day = 0.0, 
                    precip_minutes_local_yesterday = 0.0, 
                    is_precip_local_day_rain_check = False, 
                    is_precip_local_yesterday_rain_check = 1.337, ),
                forecast = weatherflow_openapi.models.better_forecast_forecast.BetterForecastForecast(
                    daily = [
                        weatherflow_openapi.models.better_forecast_daily_forecast.BetterForecastDailyForecast(
                            day_start_local = 1.6086996E+9, 
                            day_num = 23.0, 
                            month_num = 12.0, 
                            conditions = 'Clear', 
                            icon = 'clear-day', 
                            sunrise = 1608639322, 
                            sunset = 1608676362, 
                            air_temp_high = 73.0, 
                            air_temp_low = 39.0, 
                            precip_probability = 10.0, 
                            precip_icon = 'chance-rain', 
                            precip_type = 'rain', )
                        ], 
                    hourly = [
                        weatherflow_openapi.models.better_forecast_hourly_forecast.BetterForecastHourlyForecast(
                            time = 1.6087356E+9, 
                            conditions = 'Clear', 
                            icon = 'clear-day', 
                            air_temperature = 57.0, 
                            sea_level_pressure = 30.257, 
                            relative_humidity = 82.0, 
                            precip = 0.0, 
                            precip_probability = 0.0, 
                            wind_avg = 2.0, 
                            wind_direction = 34.0, 
                            wind_direction_cardinal = 'NE', 
                            wind_gust = 3.0, 
                            uv = 2.0, 
                            feels_like = 57.0, 
                            local_hour = 10.0, 
                            local_day = 23.0, )
                        ], ),
                units = weatherflow_openapi.models.better_forecast_units.BetterForecastUnits(
                    units_temp = 'f', 
                    units_wind = 'mph', 
                    units_precip = 'in', 
                    units_pressure = 'inhg', 
                    units_distance = 'mi', 
                    units_brightness = 'lux', 
                    units_solar_radiation = 'w/m2', 
                    units_other = 'imperial', 
                    units_air_density = 'lbs/ft3', ),
                latitude = 29.00724,
                longitude = -80.88067,
                timezone = 'America/New_York',
                timezone_offset_minutes = -300.0
            )
        else:
            return BetterForecast(
        )
        """

    def testBetterForecast(self):
        """Test BetterForecast"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
