# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from weatherflow_openapi.models.device import Device  # noqa: E501

class TestDevice(unittest.TestCase):
    """Device unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Device:
        """Test Device
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Device`
        """
        model = Device()  # noqa: E501
        if include_optional:
            return Device(
                device_id = 128,
                serial_number = 'AR-12345678',
                device_meta = weatherflow_openapi.models.device_meta.DeviceMeta(
                    agl = 2.2, 
                    name = 'Pool Air Device', 
                    environment = 'outdoor', 
                    wifi_network_name = '', ),
                device_type = 'AR',
                hardware_revision = '3',
                firmware_revision = '3',
                notes = ''
            )
        else:
            return Device(
        )
        """

    def testDevice(self):
        """Test Device"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
