# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weatherflow_openapi.api.forecast_api import ForecastApi  # noqa: E501


class TestForecastApi(unittest.TestCase):
    """ForecastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ForecastApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_better_forecast(self) -> None:
        """Test case for get_better_forecast

        Get Better Forecast Data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
