# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weatherflow_openapi.api.stations_api import StationsApi  # noqa: E501


class TestStationsApi(unittest.TestCase):
    """StationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StationsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_station_by_id(self) -> None:
        """Test case for get_station_by_id

        Find a Station by station_id  # noqa: E501
        """
        pass

    def test_get_stations(self) -> None:
        """Test case for get_stations

        Find all Stations for a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
