# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from weatherflow_openapi.models.better_forecast_current_conditions import BetterForecastCurrentConditions  # noqa: E501

class TestBetterForecastCurrentConditions(unittest.TestCase):
    """BetterForecastCurrentConditions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetterForecastCurrentConditions:
        """Test BetterForecastCurrentConditions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetterForecastCurrentConditions`
        """
        model = BetterForecastCurrentConditions()  # noqa: E501
        if include_optional:
            return BetterForecastCurrentConditions(
                time = 1608668142,
                conditions = 'Clear',
                icon = 'clear-day',
                air_temperature = 67.0,
                sea_level_pressure = 30.195,
                station_pressure = 30.079,
                pressure_trend = 'falling',
                relative_humidity = 55.0,
                wind_avg = 3.2,
                wind_direction = 15.0,
                wind_direction_cardinal = 'NNE',
                wind_direction_icon = 'wind-rose-nne',
                wind_gust = 3.4,
                solar_radiation = 22.0,
                uv = 0.0,
                brightness = 2582.0,
                feels_like = 68.9,
                dew_point = 50.0,
                wet_bulb_temperature = 57.0,
                delta_t = 10.0,
                air_density = 0.08,
                lightning_strike_count_last_1hr = 0.0,
                lightning_strike_count_last_3hr = 1.0,
                lightning_strike_last_distance = 7.0,
                lightning_strike_last_distance_msg = '6 - 8 mi',
                lightning_strike_last_epoch = 1608150959,
                precip_accum_local_day = 0.0,
                precip_accum_local_yesterday = 0.0,
                precip_minutes_local_day = 0.0,
                precip_minutes_local_yesterday = 0.0,
                is_precip_local_day_rain_check = False,
                is_precip_local_yesterday_rain_check = 1.337
            )
        else:
            return BetterForecastCurrentConditions(
        )
        """

    def testBetterForecastCurrentConditions(self):
        """Test BetterForecastCurrentConditions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
