# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from weatherflow_openapi.models.station_meta import StationMeta  # noqa: E501

class TestStationMeta(unittest.TestCase):
    """StationMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StationMeta:
        """Test StationMeta
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StationMeta`
        """
        model = StationMeta()  # noqa: E501
        if include_optional:
            return StationMeta(
                elevation = 33.2,
                share_with_wf = True,
                share_with_wu = True
            )
        else:
            return StationMeta(
        )
        """

    def testStationMeta(self):
        """Test StationMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
