# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from weatherflow_openapi.models.device_meta import DeviceMeta  # noqa: E501

class TestDeviceMeta(unittest.TestCase):
    """DeviceMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceMeta:
        """Test DeviceMeta
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceMeta`
        """
        model = DeviceMeta()  # noqa: E501
        if include_optional:
            return DeviceMeta(
                agl = 2.2,
                name = 'Pool Air Device',
                environment = 'outdoor',
                wifi_network_name = ''
            )
        else:
            return DeviceMeta(
        )
        """

    def testDeviceMeta(self):
        """Test DeviceMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
