# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from weatherflow_openapi.models.better_forecast_daily_forecast import BetterForecastDailyForecast  # noqa: E501

class TestBetterForecastDailyForecast(unittest.TestCase):
    """BetterForecastDailyForecast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetterForecastDailyForecast:
        """Test BetterForecastDailyForecast
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetterForecastDailyForecast`
        """
        model = BetterForecastDailyForecast()  # noqa: E501
        if include_optional:
            return BetterForecastDailyForecast(
                day_start_local = 1.6086996E+9,
                day_num = 23.0,
                month_num = 12.0,
                conditions = 'Clear',
                icon = 'clear-day',
                sunrise = 1608639322,
                sunset = 1608676362,
                air_temp_high = 73.0,
                air_temp_low = 39.0,
                precip_probability = 10.0,
                precip_icon = 'chance-rain',
                precip_type = 'rain'
            )
        else:
            return BetterForecastDailyForecast(
        )
        """

    def testBetterForecastDailyForecast(self):
        """Test BetterForecastDailyForecast"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
