# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from weatherflow_openapi.models.better_forecast_daily_forecast import BetterForecastDailyForecast
from weatherflow_openapi.models.better_forecast_hourly_forecast import BetterForecastHourlyForecast

class BetterForecastForecast(BaseModel):
    """
    BetterForecastForecast
    """
    daily: Optional[conlist(BetterForecastDailyForecast)] = None
    hourly: Optional[conlist(BetterForecastHourlyForecast)] = None
    __properties = ["daily", "hourly"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BetterForecastForecast:
        """Create an instance of BetterForecastForecast from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in daily (list)
        _items = []
        if self.daily:
            for _item in self.daily:
                if _item:
                    _items.append(_item.to_dict())
            _dict['daily'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in hourly (list)
        _items = []
        if self.hourly:
            for _item in self.hourly:
                if _item:
                    _items.append(_item.to_dict())
            _dict['hourly'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BetterForecastForecast:
        """Create an instance of BetterForecastForecast from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BetterForecastForecast.parse_obj(obj)

        _obj = BetterForecastForecast.parse_obj({
            "daily": [BetterForecastDailyForecast.from_dict(_item) for _item in obj.get("daily")] if obj.get("daily") is not None else None,
            "hourly": [BetterForecastHourlyForecast.from_dict(_item) for _item in obj.get("hourly")] if obj.get("hourly") is not None else None
        })
        return _obj


