# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr

class StationItem(BaseModel):
    """
    StationItem
    """
    location_item_id: Optional[StrictInt] = None
    station_id: Optional[StrictInt] = None
    device_id: Optional[StrictInt] = None
    item: Optional[StrictStr] = None
    __properties = ["location_item_id", "station_id", "device_id", "item"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StationItem:
        """Create an instance of StationItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StationItem:
        """Create an instance of StationItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StationItem.parse_obj(obj)

        _obj = StationItem.parse_obj({
            "location_item_id": obj.get("location_item_id"),
            "station_id": obj.get("station_id"),
            "device_id": obj.get("device_id"),
            "item": obj.get("item")
        })
        return _obj


