# coding: utf-8

"""
    WeatherFlow Tempest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: jforare@weatherflow.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from weatherflow_openapi.models.station import Station
from weatherflow_openapi.models.status import Status

class StationSet(BaseModel):
    """
    StationSet
    """
    status: Optional[Status] = None
    locations: Optional[conlist(Station)] = None
    __properties = ["status", "locations"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StationSet:
        """Create an instance of StationSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in locations (list)
        _items = []
        if self.locations:
            for _item in self.locations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['locations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StationSet:
        """Create an instance of StationSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StationSet.parse_obj(obj)

        _obj = StationSet.parse_obj({
            "status": Status.from_dict(obj.get("status")) if obj.get("status") is not None else None,
            "locations": [Station.from_dict(_item) for _item in obj.get("locations")] if obj.get("locations") is not None else None
        })
        return _obj


